
languagePack = {  }
languagePack['waiting_1'] = '出征……一段时间过后'
languagePack['waiting_2'] = '征兵……一段时间过后'
languagePack['waiting_3'] = '成功击退贼兵!'
languagePack['waiting_4'] = '战报加载中...'
languagePack['waiting_99'] = '征兵时间'
languagePack['zhengbing'] = '征兵'
languagePack['zhengbing_ing'] = '征兵中'
languagePack['all_info'] = '详'
languagePack['brief_info'] = '略'
languagePack['wenhao'] = '？？？'
languagePack['wenhao_english'] = '???'
languagePack['wan'] = '万'
languagePack['xinjian'] = '新建'
languagePack['lv'] = 'Lv.'
languagePack['none'] = '--'
languagePack['relogin'] = '注销账号'
languagePack['xiaoditu'] = '世界地图'
languagePack['dijunbingli'] = '敌军兵力'
languagePack['chengshidingwei'] = '城市定位'
languagePack['kai'] = '开'
languagePack['kaiqi'] = '开启'
languagePack['kaiqied'] = '已开启'
languagePack['tigao'] = '提高'
languagePack['tigaoed'] = '已提高'
languagePack['wancheng'] = '完成'
languagePack['gengxin'] = '更新'
languagePack['gengxined'] = '已更新'
languagePack['yijinglingqu'] = '已经领取奖励'
languagePack['jindujinxing'] = '进行中'
languagePack['kaiqishanzhai'] = '开启山寨功能'
languagePack['tigaoshanzhai'] = '提高出现山寨的等级'
languagePack['kaiqizhaomu'] = '开启EX卡包：'
languagePack['beibaoshangxian'] = '提高玩家卡牌上限至'
languagePack['zhaomudengjitigao'] = '提高%s卡包武将等级至Lv.%d'
languagePack['kabaohebing'] = '增加名将卡包招募阵容'
languagePack['dibiaoshijianzhaomu'] = '事件'
languagePack['dachengtongmeng'] = '达成同盟'
languagePack['dachengshili'] = '达成势力'
languagePack['zanwutongmengdacheng'] = '暂无同盟达成'
languagePack['zanwushilidacheng'] = '暂无势力达成'
languagePack['jieshushijian'] = '结束时间'
languagePack['dachengshijian'] = '达成时间'
languagePack['firstjiangli'] = '第一名奖励'
languagePack['firstUnionjiangli'] = '第一名同盟奖励'
languagePack['quanfuhuode'] = '全服获得'
languagePack['tongmenghuode'] = '同盟成员获得'
languagePack['weizhanling'] = '未占领'
languagePack['yijingjieshu'] = '已经结束'
languagePack['dagnqianjindu'] = '当前进度:'
languagePack['shijiejindupaiming'] = '第%d名：%s'
languagePack['localLanguageNum_1'] = '一'
languagePack['localLanguageNum_2'] = '二'
languagePack['localLanguageNum_3'] = '三'
languagePack['localLanguageNum_4'] = '四'
languagePack['localLanguageNum_5'] = '五'
languagePack['localLanguageNum_6'] = '六'
languagePack['localLanguageNum_7'] = '七'
languagePack['localLanguageNum_8'] = '八'
languagePack['localLanguageNum_9'] = '九'
languagePack['localLanguageNum_10'] = '十'
languagePack['city_create_default'] = '默认名称'
languagePack['guan'] = '关'
languagePack['jiaoqu'] = '城区'
languagePack['youxiaoshuzi'] = '请输入11位手机号码'
languagePack['yanzhengmawuxiao'] = '请输入有效验证码'
languagePack['xiangou'] = '限购'
languagePack['zhanyongmianji'] = '占用面积'
languagePack['jianzaoxuqiu'] = '建造需求'
languagePack['shengjixuqiu'] = '升级需求'
languagePack['zhunbeizhong'] = '准备'
languagePack['jianzhuduilie'] = '建筑队列'
languagePack['build_city_2'] = '建造分城'
languagePack['build_city_1'] = '在土地'
languagePack['Draft'] = '征兵队列数'
languagePack['tongmengzhanbao'] = '同盟战报'
languagePack['jianzhuzhong'] = '建造'
languagePack['cityTypeName_player_chengqu'] = '城区'
languagePack['shengjizhong'] = '升级'
languagePack['chaichuzhong'] = '拆除'
languagePack['fangqizhong'] = '放弃'
languagePack['bunengfasong'] = '不允许向自己发送邮件'
languagePack['xinchouka'] = '新的卡包'
languagePack['biancheng'] = '编成'
languagePack['julijin'] = '近'
languagePack['julizhong'] = '中'
languagePack['juliyuan'] = '远'
languagePack['dangqian'] = '当前'
languagePack['lijiwancheng'] = '立即完成'
languagePack['chaichu'] = '拆除'
languagePack['shengji'] = '升级'
languagePack['manji'] = '满级'
languagePack['jianzao'] = '建造'
languagePack['xiangqing'] = '详情'
languagePack['payagain'] = '当前礼包还没过期，无法重复购买'
languagePack['fangqi'] = '放弃'
languagePack['shengyu'] = '剩余'
languagePack['zhanlipin'] = '可能战利品'
languagePack['shengjixuyao'] = '需要'
languagePack['suoxushijian'] = '所需时间'
languagePack['quxiaochaichu'] = '取消'
languagePack['shengjishijian'] = '升级时间'
languagePack['chaichushijian'] = '拆除时间'
languagePack['shoujun'] = '守军'
languagePack['lingdi'] = '领地'
languagePack['zhengling'] = '政令'
languagePack['shui'] = '河流'
languagePack['shan'] = '山脉'
languagePack['shanzhai'] = '山寨'
languagePack['cheng'] = '城'
languagePack['ziyuandi'] = '土地'
languagePack['createtitle'] = '建造中，剩余时间'
languagePack['deletetitle'] = '放弃中，剩余时间'
languagePack['build_building'] = '建造中'
languagePack['build_upgrading'] = '升级中'
languagePack['jianshezhi'] = '面积'
languagePack['fanrongdu'] = '繁荣度'
languagePack['naijiudu'] = '耐久度  '
languagePack['yikuojiantudishu'] = '已扩建  '
languagePack['ji'] = '级'
languagePack['fangshou'] = '防守'
languagePack['gongji'] = '进攻'
languagePack['junshi'] = '军师'
languagePack['daying'] = '大营'
languagePack['zhongjun'] = '中军'
languagePack['qianfeng'] = '前锋'
languagePack['budui'] = '部队'
languagePack['xiyoudu'] = '稀有度'
languagePack['guojia'] = '国家'
languagePack['ri'] = '日'
languagePack['yue'] = '月'
languagePack['nian'] = '年'
languagePack['today'] = '今日'
languagePack['jintian'] = '今天'
languagePack['zuotian'] = '昨天'
languagePack['bingzhong'] = '兵种'
languagePack['dengji'] = '等级'
languagePack['jinenghecheng'] = '战法合成'
languagePack['yixuanzhe'] = '已选择'
languagePack['qianghua'] = '强化'
languagePack['xuexi'] = '学习'
languagePack['queren'] = '确认'
languagePack['tuntian'] = '屯田'
languagePack['training'] = '练兵'
languagePack['xidelv'] = '习得率'
languagePack['wu'] = '无'
languagePack['deng'] = '队'
languagePack['one'] = '一'
languagePack['two'] = '二'
languagePack['three'] = '三'
languagePack['four'] = '四'
languagePack['five'] = '五'
languagePack['xingqiyi'] = '星期一'
languagePack['xingqier'] = '星期二'
languagePack['xingqisan'] = '星期三'
languagePack['xingqisi'] = '星期四'
languagePack['xingqiwu'] = '星期五'
languagePack['xingqiliu'] = '星期六'
languagePack['xingqiri'] = '星期日'
languagePack['maohao'] = '：'
languagePack['people'] = '将'
languagePack['cancel'] = '取消'
languagePack['goto_pay'] = '前往充值'
languagePack['goto_transferSkillValue'] = '战法经验转化'
languagePack['lijifanhui'] = '立即撤退'
languagePack['fanhui'] = '撤退'
languagePack['chuzheng'] = '出征'
languagePack['zhuzha'] = '调动'
languagePack['diaodong'] = '调动'
languagePack['zhushou'] = '驻守'
languagePack['saodang'] = '扫荡'
languagePack['daiming'] = '待命'
languagePack['zhanjianxiuxi'] = '休整'
languagePack['dixi'] = '敌袭'
languagePack['chetui'] = '撤退'
languagePack['shuai'] = '率'
languagePack['normal_zhong'] = '待命'
languagePack['xingjun_zhong'] = '行军'
languagePack['fanhui_zhong'] = '撤退'
languagePack['zhuzha_zhong'] = '待命'
languagePack['yuanjun_zhong'] = '驻守'
languagePack['bingli'] = '兵力  '
languagePack['diaodong_tips'] = '驻守可保护周围我方及友方地块，战斗不回复伤兵'
languagePack['zhuzha_tips'] = '可以从要塞出征，调动时间为普通行军的1/3'
languagePack['teach_des_1'] = '初始战法'
languagePack['teach_des_2'] = '等级越高，传授战法越丰富，概率越高'
languagePack['chengzhang'] = '成长：'
languagePack['inarmy'] = '部队中'
languagePack['selectmaterial'] = '选择素材'
languagePack['zhongshang'] = '重伤'
languagePack['chanliangtigao'] = '产量提高'
languagePack['shibai'] = '失败'
languagePack['gong'] = '攻'
languagePack['shou'] = '守'
languagePack['weishangbang'] = '未上榜'
languagePack['wodepaiming'] = '我的排名'
languagePack['benmengpaiming'] = '本盟排名'
languagePack['jiarutongmeng'] = '加入同盟'
languagePack['player_rank_des'] = '如下项目可增加个人势力值'
languagePack['union_rank_des'] = '同盟势力值与同盟等级、同盟经验、同盟占领的守军城池数有关，各等级守军城池可增加的同盟势力值如下：'
languagePack['huode'] = '获得'
languagePack['mucai'] = '木材'
languagePack['shikuai'] = '石料'
languagePack['tiekuai'] = '铁矿'
languagePack['liangshi'] = '粮草'
languagePack['jiqiao'] = '战法经验'
languagePack['bingliangxiaohao'] = '维持粮耗  '
languagePack['liangshichanliang'] = '粮草产量'
languagePack['buduizhandoushuxing'] = '本城部队属性加成'
languagePack['xiaoshi'] = '小时'
languagePack['tongqian'] = '铜钱'
languagePack['gain'] = '获得'
languagePack['award'] = '奖励'
languagePack['new'] = '新'
languagePack['jin'] = '玉符'
languagePack['buildQueue'] = '建造队列'
languagePack['free_first'] = '首张免费'
languagePack['mianfei'] = '免费'
languagePack['half_price'] = ' (半价)'
languagePack['free_refresh'] = '免费刷新'
languagePack['shengyucishu'] = '剩余次数'
languagePack['mianfeicishu'] = '免费次数'
languagePack['dailycishu'] = '次数'
languagePack['xiacimianfei'] = '后 免费'
languagePack['xiaoshidaoji'] = '后 消失'
languagePack['hebingdaoji'] = '后并入'
languagePack['daily_reset'] = '0点重置'
languagePack['hufu_han'] = '虎符·汉'
languagePack['hufu_wei'] = '虎符·魏'
languagePack['hufu_shu'] = '虎符·蜀'
languagePack['hufu_wu'] = '虎符·吴'
languagePack['hufu_qun'] = '虎符·群'
languagePack['jiangjunyin'] = '将军印'
languagePack['meizhang'] = '/张'
languagePack['leave_time'] = '剩余时间：'
languagePack['weipeizhi'] = '未配置'
languagePack['weizhushou'] = '无部队'
languagePack['kaifang'] = '开放'
languagePack['xuyao'] = '需要'
languagePack['zb_num'] = '征兵数量：'
languagePack['dangqianbingli'] = '当前兵力：'
languagePack['yujishijian'] = '预计用时：'
languagePack['yubeibingnotime'] = '立即转为士兵'
languagePack['yujingshijian'] = '预警时间：'
languagePack['junshibianzhi'] = '军师编制：'
languagePack['zhongjunbianzhi'] = '中军编制：'
languagePack['jiasu'] = '加速'
languagePack['weijian'] = '未建造'
languagePack['mianji'] = '面积'
languagePack['zaiye'] = '在野'
languagePack['chengyuan'] = '成员'
languagePack['mengzhu'] = '盟主'
languagePack['fumengzhu'] = '副盟主'
languagePack['guanyuan'] = '官员'
languagePack['linyuanshi'] = '林掾史'
languagePack['shifangling'] = '石坊令'
languagePack['wukushi'] = '武库史'
languagePack['jitianling'] = '籍田令'
languagePack['jianshili'] = '监市吏'
languagePack['huangmenzhongchen'] = '黄门中丞'
languagePack['xiyuantiwei'] = '西园廷卫'
languagePack['bingcao'] = '兵曹'
languagePack['jijiu'] = '祭酒'
languagePack['region_border'] = '边界'
languagePack['taolunban'] = '讨论版'
languagePack['zhanbaorizhi'] = '战报日志'
languagePack['zhisuo'] = '治所'
languagePack['juanzeng'] = '捐赠'
languagePack['tongmengjiacheng'] = '同盟加成'
languagePack['tongmengjudianjiacheng'] = '同盟城池加成'
languagePack['xiashuchengyuan'] = '下属'
languagePack['gonggao'] = '公 告'
languagePack['fangyubudui'] = '防御部队强化  '
languagePack['tongmengnengli'] = '同盟能力'
languagePack['shenqingjiaru'] = '申请加入'
languagePack['querenjuanzeng'] = '确认捐赠'
languagePack['quxiaoshenqing'] = '取消申请'
languagePack['jianlitongmeng'] = '建立同盟'
languagePack['xiangxixinxi'] = '详细信息'
languagePack['quxiaoshanrang'] = '取消禅让'
languagePack['yichuchengyuan'] = '移除成员'
languagePack['shenqingren'] = '申请人'
languagePack['res_not_enough_gold'] = '玉符不足'
languagePack['res_not_enough_coin'] = '铜钱不足'

languagePack['qingkong'] = '清空'
languagePack['jujuesuoxuan'] = '拒绝'
languagePack['tongyisuoxuan'] = '同意'
languagePack['shenqingshijian'] = '申请时间'
languagePack['xuanze'] = '选择'
languagePack['shanrang'] = '禅让'
languagePack['xieren'] = '卸任'
languagePack['jingyan'] = '经验'
languagePack['mingwang'] = '名望'
languagePack['tongzhidian'] = '预备兵'
languagePack['shurutongmengming'] = '输入同盟名'
languagePack['qingshurusuojianlitongmengdemingchen'] = '请输入所建立同盟的名称'
languagePack['tongmengmingzibunengweikong'] = '同盟名称不能为空'
languagePack['tongmengmingzizuiduo'] = '同盟名称最多八个字'
languagePack['zuiduobagezi'] = '最多六个字'
languagePack['wanchengrenwu'] = '完成任务'
languagePack['weijiarutongmeng'] = '未加入同盟'
languagePack['liquan'] = '礼券'
languagePack['fanpan'] = '确认反叛'
languagePack['mengyou'] = '盟友'
languagePack['haoyou'] = '好友'
languagePack['fasong'] = '发送'
languagePack['yanzhengshibai'] = '获取验证码失败'
languagePack['shuruyanzhengcuowu'] = '验证码输入错误'
languagePack['zhengzaiyanzheng'] = '验证码已发出，若没收到，请60秒后再次获取'
languagePack['tongmengjuanzeng'] = '同盟捐赠'
languagePack['tongmengfanpan'] = '同盟反叛'
languagePack['tongmengdengji'] = '同盟等级'
languagePack['fanpanjindu'] = '反叛进度'
languagePack['shangjiaoziyuan'] = '上缴资源'
languagePack['shangjiao'] = '上交'
languagePack['xuanzheshoujianren'] = '选择收件人'
languagePack['fasongchenggong'] = '发送成功'
languagePack['shoujianrenbunengweikong'] = '请添加收件人'
languagePack['zhengwenbunengweikong'] = '请输入正文'
languagePack['bunenggeiziji'] = '不能给自己发邮件'
languagePack['notmailblack'] = '不能向黑名单中的势力发送邮件'
languagePack['guanwei'] = '官位'
languagePack['tuichubianji'] = '退出编辑'
languagePack['qingshurushoujianren'] = '请输入收件人'
languagePack['qingshuruyoujianbiaoti'] = '请输入邮件标题'
languagePack['qingshuruzhengwen'] = '请输入正文'
languagePack['shanchu'] = '删除'
languagePack['quanxuan'] = '全选'
languagePack['queding'] = '确定'
languagePack['fanhuipeizhi'] = '返回'
languagePack['luxiang'] = '战况回放'
languagePack['chengyuanming'] = '成员'
languagePack['shoujianxiang'] = '收件箱'
languagePack['xitongyoujian'] = '系统邮件'
languagePack['xinyoujian'] = '新邮件'
languagePack['fajianxiang'] = '发件箱'
languagePack['fajianren'] = '发件人'
languagePack['shoujianren'] = '收件人'
languagePack['bianji'] = '编辑'
languagePack['renwumubiao'] = '目标'
languagePack['renwumiaoshu'] = '描述'
languagePack['renwujiangli'] = '奖励'
languagePack['reply'] = '  回复'
languagePack['yilingqu'] = '  已领取'
languagePack['getBonus'] = '领取'
languagePack['alreadygetBonus'] = '已领取'
languagePack['julibuzu'] = '距离不足'
languagePack['lingqufujian'] = '领取'
languagePack['zonggongxianzhi'] = '贡献'
languagePack['shenqingzhong'] = '申请中'
languagePack['jiesantongmeng'] = '解散同盟'
languagePack['tuichutongmeng'] = '退出同盟'
languagePack['juanzengjingyan'] = '贡献'
languagePack['zongbingli'] = '总兵力'
languagePack['notestablished'] = '未建立'
languagePack['skillUnlockLessOfSameNameCard'] = '需要相同卡'
languagePack['skillTipsHightQuality'] = '稀有'
languagePack['skillTipsLearnedSkill'] = '已强化/学习战法'
languagePack['skillTipsStrengthedSkill'] = '已强化/学习战法'
languagePack['skillTipsSelected'] = '已选定'
languagePack['skillTipsUpgraded'] = '已升级'
languagePack['skillTipsProtected'] = '已保护'
languagePack['skillTipsUnlocked'] = '已觉醒'
languagePack['skillTipsAdvanced'] = '已进阶'
languagePack['skillTipsAllocatedPoint'] = '已配点'
languagePack['bingding'] = '绑定成功'
languagePack['arms_title'] = '兵种加成'
languagePack['camp_title'] = '阵营加成'
languagePack['wj_group_title'] = '称号加成'
languagePack['arms_tips'] = '配置不少于2张相同兵种武将卡可激活'
languagePack['camp_tips'] = '建造点将台&配置不少于2张同阵营武将卡可激活'
languagePack['wj_group_tips'] = '配置指定武将组合可激活'
languagePack['exercise_camp_tips'] = '无阵营加成'
languagePack['land_tips_1'] = '无法占领'
languagePack['land_tips_2'] = '无主'
languagePack['land_tips_3'] = '同盟占领'
languagePack['server_title'] = '区'
languagePack['announcement'] = '公告'
languagePack['role_forces_edit_intro'] = '介绍（最多100字）'
languagePack['ranger_confirm'] = '流浪'
languagePack['move_city_confirm'] = '迁城'
languagePack['date_day'] = '天'
languagePack['date_month'] = '月'
languagePack['general_card'] = '武将卡'
languagePack['illegal_operate'] = '非法操作 未定义提示'
languagePack['trade_title_res'] = '待交易资源'
languagePack['trade_title_target_res'] = '目标资源'
languagePack['union_country_city'] = '国都'
languagePack['union_capital'] = '州府'
languagePack['union_stronghold'] = '城池'
languagePack['union_checkpoint'] = '关'
languagePack['union_position_null'] = '空缺'
languagePack['chat_default'] = '发送内容不超过60字'
languagePack['chat_default_error'] = '发送内容超过60字'
languagePack['gameSprite_max_num'] = '发送内容超过15字'
languagePack['chat_null_personal'] = '暂无聊天信息'
languagePack['chat_null_union'] = '暂无同盟信息'
languagePack['chat_null_sys'] = '暂无系统信息'
languagePack['chat_null_region'] = '本州暂无聊天内容'
languagePack['chat_interval_limit'] = '发言频率过快'
languagePack['chat_openstate_tips'] = '名望达到@&@后开放'
languagePack['country_type_han'] = '汉'
languagePack['country_type_wei'] = '魏'
languagePack['country_type_shu'] = '蜀'
languagePack['country_type_wu'] = '吴'
languagePack['country_type_qun'] = '群'
languagePack['guodu'] = '国都'
languagePack['zhoufu'] = '州府'
languagePack['chengchi'] = '城池'
languagePack['guanqia'] = '关卡'
languagePack['ForcesSoldier'] = '预备兵力'
languagePack['buildingAreaTitleMainCity'] = '城主府'
languagePack['buildingAreaTitleMilitary'] = '军事设施'
languagePack['buildingAreaTitleInterior'] = '内政设施'
languagePack['tax_title'] = '税收'
languagePack['date_yesterday'] = '昨天'
languagePack['date_hour_ago'] = '小时前'
languagePack['date_min_ago'] = '分钟前'
languagePack['date_min'] = '分'
languagePack['date_sec'] = '秒'
languagePack['date_a_moument'] = '刚刚'
languagePack['fasongyoujian'] = '发送邮件'
languagePack['shilixinxi'] = '势力信息'
languagePack['gerenxinxi'] = '个人信息'
languagePack['jiaruheimingdan'] = '加入黑名单'
languagePack['intro_zhucheng'] = '城主府是城市的中心建筑，控制城市的主要功能'
languagePack['intro_fenchengcheng'] = '城主府是分城的中心建筑，控制分城的主要功能'
languagePack['intro_yaosai'] = '堡垒是要塞的中心建筑，控制要塞的主要功能'
languagePack['giving_up'] = '放弃中'
languagePack['everyday_bonus'] = '每天额外赠送'
languagePack['extra_bonus'] = '额外赠送'
languagePack['noAnnouncement'] = '暂无公告'
languagePack['function_open'] = '开放'
languagePack['build_condition'] = '建造条件'
languagePack['grade_name'] = '级'

languagePack['actived'] = '已激活'
languagePack['unactived'] = '满级激活'

languagePack['reportEmptyTips'] = '暂无战报'
languagePack['reportEmptyTipsUnion'] = '暂无同盟战报'

languagePack['functionUnopenTips'] = '暂未开放，敬请期待'
languagePack['functionOpenOnly_prefix'] = '目前只开放'
languagePack['name_personalProper'] = '个人城区'
languagePack['name_defenderProper'] = '守军城区'

languagePack['gift_exchange_code_default'] = '请输入礼包码'
languagePack['cardProtectState_active'] = '保护'
languagePack['cardProtectState_passtive'] = '未保护'

languagePack['wujiang'] = '武将'
languagePack['heroCardLvName'] = '星'
languagePack['above'] = '以上'

languagePack['yanwu'] = '沙盘演武'
languagePack['jiaoxue'] = '教学演武'
languagePack['ziyou'] = '自由演武'
languagePack['cishu'] = '次'
languagePack['exercise_tips_1'] = '请选择目标部队'
languagePack['exercise_tips_2'] = '下一轮演武 '
languagePack['exercise_tips_3'] = '点击下一轮开启新的演武'
languagePack['exercise_tips_4'] = '每天0点回复演武次数'
languagePack['condition_1'] = '战胜所有部队'
languagePack['condition_2'] = '战胜目标部队'
languagePack['next_exercise'] = '下一轮'

languagePack['taxForceRevenue_rewardTips'] = '#本次强征收取【#@&@#铜】#'
languagePack['land_res_type_name_1'] = '木材'
languagePack['land_res_type_name_2'] = '石料'
languagePack['land_res_type_name_3'] = '铁矿'
languagePack['land_res_type_name_4'] = '粮食'
languagePack['land_res_type_name_5'] = '铜钱'
languagePack['land_res_type_name_6'] = '骑兵攻击'
languagePack['land_res_type_name_7'] = '骑兵防御'
languagePack['land_res_type_name_8'] = '骑兵谋略'
languagePack['land_res_type_name_9'] = '骑兵速度'
languagePack['land_res_type_name_10'] = '弓兵攻击'
languagePack['land_res_type_name_11'] = '弓兵防御'
languagePack['land_res_type_name_12'] = '弓兵谋略'
languagePack['land_res_type_name_13'] = '弓兵速度'
languagePack['land_res_type_name_14'] = '步兵攻击'
languagePack['land_res_type_name_15'] = '步兵防御'
languagePack['land_res_type_name_16'] = '步兵谋略'
languagePack['land_res_type_name_17'] = '步兵速度'

----------------------------------------------------------------------------------
------------------------------土地标记相关----------------------------------------
----------------------------------------------------------------------------------
languagePack['land_mark_fail_maxCountLimit'] = '已达到标记上限'
languagePack['land_mark_succeed_marked'] = '标记成功'
languagePack['land_mark_succeed_unmarked'] = '取消标记成功'
languagePack['land_mark_succeed_deleteMarked'] = '删除标记成功'

------------- 战法相关 ------------------
languagePack['hero_second_skill_able'] = '可学习'
languagePack['hero_second_skill_unable'] = '武将Lv5'
languagePack['hero_third_skill_able'] = '可觉醒'
languagePack['hero_third_skill_unable'] = '未觉醒'

languagePack['hero_second_skill_unopen_tips'] = '武将Lv.5开放'

--------------------------
languagePack['army_move_tips_cannot_reside'] = '目标地不允许驻扎'
----------------------------------------------------------------------------------
--------------地表事件相关
languagePack['ground_event_title_name'] = '事件'
languagePack['ground_event_card'] = '散落在土地上的武将卡包。'
languagePack['ground_event_exp'] = '散落在土地上的武将经验书。'
languagePack['ground_event_thief'] = '不知从何处抢夺来一些资源的贼兵。'

languagePack['ground_event_card_log'] = '@&@#的部队到达了土地(#@&@#,#@&@#)，获得了#@&@#。#'
languagePack['ground_event_exp_log'] = '@&@#的部队到达了土地(#@&@#,#@&@#)，获得了#@&@@&@#。#'
languagePack['ground_event_thief_log_win'] = '#胜利：#@&@#的部队到达了土地(#@&@#,#@&@#),并战胜贼兵，获得了#@&@@&@#。#'
languagePack['ground_event_thief_log_lose'] = '#失败：#@&@#的部队到达了土地(#@&@#,#@&@#),但惜败于贼兵，未能获得资源奖励。#'

----------------------------------------------------------------------------------
------------------------------土地详情相关----------------------------------------
----------------------------------------------------------------------------------
languagePack['land_intro_lv_6'] = '#土地Lv.6上建分城，可建造#@钱庄@#(提升本城税收)#'
languagePack['land_intro_lv_7'] = '#土地Lv.7上建分城，可建造#@技工所@#(提升本城资源产量)#'
languagePack['land_intro_lv_8'] = '#土地Lv.8上建分城，可建造#@塔楼@#(提升本城视野范围)#'
languagePack['land_intro_lv_9'] = '#土地Lv.9上建分城，可建造#@酒馆@#(加快本城武将体力恢复)#'

languagePack['land_yaosai'] = '个人占领，可调动放置2支部队，允许1支部队在内征兵'
languagePack['land_yunying'] = '个人占领，可调动放置2支部队，允许1支部队在内征兵，存有少量预备兵'



----------------------------------------------------------------------------------
------------------------------登陆奖励相关----------------------------------------
----------------------------------------------------------------------------------
languagePack['ui_login_detail_title_today'] = '今日登录奖励'
languagePack['ui_login_detail_title_dayth'] = '登录第#天奖励'
----------------------------------------------------------------------------------

--------------------------------------------------------------------------
--------- 行军列表相关
--------------------------------------------------------------------------
languagePack['armyManager_noneListTips_1'] = '暂无行军中的部队'
languagePack['armyManager_noneListTips_2'] = '暂无驻守中的部队'
languagePack['armyManager_noneListTips_3'] = '暂无待命中的部队'
languagePack['armyManager_noneListTips_4'] = '暂无敌袭中的部队'
--------------------------------------------------------------------------
--------- 土地名字
--------------------------------------------------------------------------
languagePack['cityTypeName_own_free'] = ''
languagePack['cityTypeName_zhucheng'] = '主城'
languagePack['cityTypeName_lingdi'] = '领地'
languagePack['cityTypeName_fencheng'] = '分城'
languagePack['cityTypeName_yaosai'] = '要塞'
languagePack['cityTypeName_matou'] = '码头'
languagePack['cityTypeName_cunzhuang'] = '城区'
languagePack['cityTypeName_npc_cheng'] = 'npc城'
languagePack['cityTypeName_shanmai'] = '山脉'
--------------------------------------------------------------------------
--------- 盟友关系
--------------------------------------------------------------------------
languagePack['mapAreaRelationName_all_free'] = '无主'
languagePack['mapAreaRelationName_own_self'] = '自己'
languagePack['mapAreaRelationName_free_ally'] = '自由状态-盟友'
languagePack['mapAreaRelationName_free_underling'] = '自由状态-下属'
languagePack['mapAreaRelationName_free_enemy'] = '自由状态-敌对'
languagePack['mapAreaRelationName_attach_higher_up'] = '附属状态-上级'
languagePack['mapAreaRelationName_attach_same_higher'] = '附属状态-同上级'
languagePack['mapAreaRelationName_attach_enemy'] = '附属状态-敌对'
languagePack['mapAreaRelationName_attach_free'] = '附属状态-无主'
--------------------------------------------------------------------------
--------- 英雄类型
--------------------------------------------------------------------------
languagePack['heroTypeName_1'] = '弓'
languagePack['heroTypeName_2'] = '步'
languagePack['heroTypeName_3'] = '骑'
languagePack['heroTypeSoldierName_1'] = '弓兵'
languagePack['heroTypeSoldierName_2'] = '步兵'
languagePack['heroTypeSoldierName_3'] = '骑兵'
--------------------------------------------------------------------------
--------- 国家类型
--------------------------------------------------------------------------
languagePack['countryName_1'] = '汉'
languagePack['countryName_2'] = '魏'
languagePack['countryName_3'] = '蜀'
languagePack['countryName_4'] = '吴'
languagePack['countryName_5'] = '群'
--------------------------------------------------------------------------
--------- 战法类型
--------------------------------------------------------------------------
languagePack['heroSkillTypeName_1'] = '被动'
languagePack['heroSkillTypeName_2'] = '指挥'
languagePack['heroSkillTypeName_3'] = '主动'
languagePack['heroSkillTypeName_4'] = '追击'
languagePack['heroSkillTypeName_5'] = '军师加成'
languagePack['heroSkillTypeName_61'] = '建筑加成一'
languagePack['heroSkillTypeName_62'] = '建筑加成二'
languagePack['heroSkillTypeName_7'] = '国家加成'
languagePack['heroSkillTypeName_8'] = '兵种加成'
languagePack['heroSkillTypeName_9'] = '称号加成'
languagePack['heroSkillTypeName_10'] = '兵种相克'

languagePack['skillLimitForCounsellor_1'] = '无限制'
languagePack['skillLimitForCounsellor_2'] = '军师限制'
languagePack['skillLimitForCounsellor_3'] = '非军师'
--------------------------------------------------------------------------
--------- 战法操作
--------------------------------------------------------------------------
languagePack['skillStrength_notFoundMaterial'] = '没有可用的素材卡'
--------------------------------------------------------------------------
--------- 战法触发概率
--------------------------------------------------------------------------
languagePack['skillUserRate_1'] = '低'
languagePack['skillUserRate_2'] = '中'
languagePack['skillUserRate_3'] = '高'
languagePack['skillUserRate_4'] = '必'
--------------------------------------------------------------------------
--------- 战法攻击范围
--------------------------------------------------------------------------
languagePack['skillAttackDes_1'] = '自己'
languagePack['skillAttackDes_2'] = '友军单体'
languagePack['skillAttackDes_3'] = '我军单体'
languagePack['skillAttackDes_4'] = '敌军单体'
languagePack['skillAttackDes_5'] = '我军群体'
languagePack['skillAttackDes_6'] = '我军群体'
languagePack['skillAttackDes_7'] = '友军群体'
languagePack['skillAttackDes_8'] = '友军群体'
languagePack['skillAttackDes_9'] = '敌军群体'
languagePack['skillAttackDes_10'] = '敌军群体'
languagePack['skillAttackDes_11'] = '攻击目标'
languagePack['skillAttackDes_12'] = '(有效距离内2-3个目标)'
languagePack['skillAttackDes_13'] = '(有效距离内1-'
languagePack['skillAttackDes_14'] = '个目标)'
languagePack['skillAttackDes_15'] = '(有效距离内'
--------------------------------------------------------------------------
--------- 土地出征提示
--------------------------------------------------------------------------
languagePack['fightPowerEstimate_1'] = '敌军实力弱小，可兵不血刃胜之'
languagePack['fightPowerEstimate_2'] = '谨慎对敌，损失在所难免'
languagePack['fightPowerEstimate_3'] = '敌军不弱，杀敌一千亦会自损八百'
languagePack['fightPowerEstimate_4'] = '敌军强盛，如无十分把握，不可以卵击石'
languagePack['fightPowerEstimate_5'] = '探索此地，不与守军战斗'
languagePack['fightPowerEstimate_6'] = '领地数已达上限，无法占领'
languagePack['fightPowerEstimate_7'] = '在野身份，无法附属目标'
languagePack['fightPowerEstimate_8'] = '敌情难测，请斟酌行事'
languagePack['fightPowerEstimate_9'] = '沦陷状态，无法附属目标'
languagePack['fightPowerEstimate_10'] = '在野状态，无法占领目标'
languagePack['fightPowerEstimate_11'] = '免战中，无法攻击'
languagePack['fightPowerEstimate_12'] = '前往目标领地与贼兵发生战斗'


--------------------------------------------------------------------------
--------- 战报相关提示
--------------------------------------------------------------------------
languagePack['REPORT_STR_2'] = '成功占领'
languagePack['REPORT_STR_3'] = '同盟占领'
languagePack['REPORT_STR_4'] = '成功附属'
languagePack['REPORT_STR_5'] = '成功解救'

languagePack['REPORT_DEF_STR_2'] = '失去领地'
languagePack['REPORT_DEF_STR_3'] = '失去领地'
languagePack['REPORT_DEF_STR_4'] = '被附属'
languagePack['REPORT_DEF_STR_5'] = '被解救'

languagePack['REPORT_ACT_1'] = '#使#@d@#的耐久下降#@d@'
languagePack['REPORT_ACT_2'] = '#占领领地#@d@'
languagePack['REPORT_ACT_3'] = '#本同盟占领城池#@d@'
languagePack['REPORT_ACT_4'] = '#附属了#@d@'
languagePack['REPORT_ACT_5'] = '#使#@d@#从附属中脱离#'

languagePack['REPORT_DEF_1'] = '@d@#耐久值下降#@d@'
languagePack['REPORT_DEF_2'] = '#失去领地#@d@'
languagePack['REPORT_DEF_3'] = '#本同盟失去城池#@d@'
languagePack['REPORT_DEF_4'] = '#被#@d@#附属#'
languagePack['REPORT_DEF_5'] = '#被#@d@#解救，脱离附属状态#'

languagePack['demolish_battle'] = '#成功拆除#@d@'
--------------------------------------------------------------------------
--------- 任务类型
--------------------------------------------------------------------------
languagePack['taskType_1'] = '主线'
languagePack['taskType_2'] = '每日'
languagePack['taskType_3'] = '活动'
--------------------------------------------------------------------------
--------- 建筑树显示的建筑名称
--------------------------------------------------------------------------
languagePack['buildingName_12'] = '都督府'
languagePack['buildingName_10'] = '城主府'
languagePack['buildingName_11'] = '堡垒'
languagePack['buildingName_2'] = '经济'
languagePack['buildingName_3'] = '部队'
languagePack['buildingName_4'] = '点将'
languagePack['buildingName_5'] = '城防'
languagePack['buildingName_6'] = '社稷坛'
languagePack['buildingName_7'] = '封禅台'
--------------------------------------------------------------------------
--------- 部队调动状态标志
--------------------------------------------------------------------------
languagePack['armyEnterState_1'] = '攻'
languagePack['armyEnterState_2'] = '调'
languagePack['armyEnterState_3'] = '守'
languagePack['armyEnterState_4'] = '退'
languagePack['armyEnterState_5'] = '袭'
--------------------------------------------------------------------------
--------- 产出加成类型
--------------------------------------------------------------------------
languagePack['union_add_defined_1'] = '武将经验'
languagePack['union_add_defined_2'] = '木材产量'
languagePack['union_add_defined_3'] = '石料产量'
languagePack['union_add_defined_4'] = '铁矿产量'
languagePack['union_add_defined_5'] = '粮草产量'
languagePack['union_add_defined_6'] = '弓兵攻击'
languagePack['union_add_defined_7'] = '弓兵防御'
languagePack['union_add_defined_8'] = '弓兵谋略'
languagePack['union_add_defined_9'] = '步兵攻击'
languagePack['union_add_defined_10'] = '步兵防御'
languagePack['union_add_defined_11'] = '步兵谋略'
languagePack['union_add_defined_12'] = '骑兵攻击'
languagePack['union_add_defined_13'] = '骑兵防御'
languagePack['union_add_defined_14'] = '骑兵谋略'
languagePack['union_add_defined_15'] = '税收'
--------------------------------------------------------------------------
--------- 武将卡出生属性描述
--------------------------------------------------------------------------
languagePack['born_card_des_1'] = '中攻 高防 高智 攻距2'
languagePack['born_card_des_2'] = '中攻 中防 中智 攻距3'
languagePack['born_card_des_3'] = '高攻 高防 低智 攻距1'
--------------------------------------------------------------------------
--------- 筑城相关描述
--------------------------------------------------------------------------
languagePack['create_city_title'] = '筑城(分城)'
languagePack['create_fort_title'] = '筑城(要塞)'
languagePack['client_cfg_city_des_1'] = '与主城类似，可在城中进行各类设施的建造，并可配置部队。'
languagePack['client_cfg_city_des_2'] = '可以调动放置部队到要塞中，并允许1支部队在内征兵。适合前线征战的部队休整。'
languagePack['client_cfg_city_attention_1'] = '1.分城建造需要占领3x3的领地，同时失去领地产量。'
languagePack['client_cfg_city_attention_2'] = '2.分城可被其他势力攻占并摧毁成废墟。'
languagePack['client_cfg_fort_attention_1'] = '建造要塞，该领地失去产量。'
languagePack['client_cfg_high_des_11'] = '钱庄'
languagePack['client_cfg_high_des_12'] = '铜钱产出）'
languagePack['client_cfg_high_des_21'] = '技工所'
languagePack['client_cfg_high_des_22'] = '资源产出）'
languagePack['client_cfg_high_des_31'] = '岗哨'
languagePack['client_cfg_high_des_32'] = '视野）'
languagePack['client_cfg_high_des_41'] = '酒馆'
languagePack['client_cfg_high_des_42'] = '提高体力回复速度'
--------------------------------------------------------------------------
--------- 同盟操作提示
--------------------------------------------------------------------------
languagePack['unionLogTable_10'] = '@&@# 成功建立#'
languagePack['unionLogTable_11'] = '#同盟等级提升为 #@Lv.&@'
languagePack['unionLogTable_12'] = '@&@# 调整了同盟公告#'
languagePack['unionLogTable_13'] = '@&@# 关闭了同盟申请#'
languagePack['unionLogTable_14'] = '@&@# 开启了同盟申请#'

languagePack['unionLogTable_20'] = '@&@# 加入了同盟#'
languagePack['unionLogTable_21'] = '@&@# 将 #@&@# 移出同盟#'
languagePack['unionLogTable_22'] = '@&@# 离开了同盟#'
languagePack['unionLogTable_23'] = '@&@# 将 #@&@# 任命为 #@&@'
languagePack['unionLogTable_24'] = '@&@# 罢免了 #@&@# 的 #@&@# 官位#'
languagePack['unionLogTable_25'] = '@&@# 卸任了副盟主#'
languagePack['unionLogTable_26'] = '@&@# 将盟主禅让给 #@&@#, #@&@#成为新的盟主#'

languagePack['unionLogTable_30'] = '#同盟成功占领国都 #@&(Lv.&)@'
languagePack['unionLogTable_31'] = '#同盟成功占领州府 #@&(Lv.&)@'
languagePack['unionLogTable_32'] = '#同盟成功占领关卡 #@&(Lv.&)@'
languagePack['unionLogTable_33'] = '#同盟成功占领城池 #@&(Lv.&)@'
languagePack['unionLogTable_34'] = '#同盟失去国都 #@&(Lv.&)@'
languagePack['unionLogTable_35'] = '#同盟失去州府 #@&(Lv.&)@'
languagePack['unionLogTable_36'] = '#同盟失去关卡 #@&(Lv.&)@'
languagePack['unionLogTable_37'] = '#同盟失去城池 #@&(Lv.&)@'
languagePack['unionLogTable_38'] = '#同盟扩张势力范围至 #@&@'
languagePack['unionLogTable_39'] = '#同盟从 #@&@# 失去势力范围#'

languagePack['unionLogTable_40'] = '@&@# 的主城被攻击#'
languagePack['unionLogTable_41'] = '@&@# 被攻击失去分城#'
languagePack['unionLogTable_42'] = '@&@# 沦陷于同盟#@&@'
languagePack['unionLogTable_43'] = '@&@# 脱离附属#'
languagePack['unionLogTable_44'] = '@&@# 被 #@&@# 解救#'
languagePack['unionLogTable_45'] = '#由于 #@&@# 的攻击，#@&@# 沦陷#'

languagePack['unionLogTable_51'] = '#对 #@&@# 的攻击开始#'
languagePack['unionLogTable_52'] = '@&@# 的守军全灭#'
languagePack['unionLogTable_56'] = '@&@# 成功攻占 #@&@@-城区@'
languagePack['unionLogTable_61'] = '#同盟成功获得国都 #@&(Lv.&)@#首杀，灭敌前三名：#@&@#，攻城前三名：#@&@'
languagePack['unionLogTable_62'] = '#同盟成功获得州府 #@&(Lv.&)@#首杀，灭敌前三名：#@&@#，攻城前三名：#@&@'
languagePack['unionLogTable_63'] = '#同盟成功获得关卡 #@&(Lv.&)@#首杀，灭敌前三名：#@&@#，攻城前三名：#@&@'
languagePack['unionLogTable_64'] = '#同盟成功获得城池 #@&(Lv.&)@#首杀，灭敌前三名：#@&@#，攻城前三名：#@&@'

languagePack['zb_title'] = '确认'
languagePack['shifouqueren'] = '#是否确认：#'
languagePack['zb_use_time'] = '##@&@#征兵#@&@#，耗时#@&@##'
languagePack['zb_unuse_time'] = '对@&@使用预备兵征兵可立即获得士兵@&@'

languagePack['union_notice_default'] = '点击输入公告内容'
languagePack['union_invite_edit_default'] = '请输入玩家名字'
---------------------------------新手引导相关----------------------------------------
languagePack['dialog_cfg_info_1'] = '大伙加把劲！\n拿下这座城，要钱有钱，要粮有粮，好日子就要来了，哈哈哈···'
languagePack['dialog_cfg_info_2'] = '您为何会在当下、城池危亡之际出现？莫非，天意如此…'
languagePack['dialog_cfg_info_3'] = '目前多处城区已经被攻陷，城内尚有部分守军，却已无将统兵…'
languagePack['dialog_cfg_info_4'] = '此时，城外却有一骑，绝尘而至。'
languagePack['dialog_cfg_info_36'] = '天不亡我！此城有救了！'
languagePack['dialog_cfg_info_5'] = '#大营#是部队的基础，配置武将后才能形成部队。\n#切记：战斗中大营若亡，此战即败。#'
languagePack['dialog_cfg_info_6'] = '愿您初战告捷！'
languagePack['dialog_cfg_info_7'] = '恭喜您再获大胜，成功收复领地。'
languagePack['dialog_cfg_info_8'] = '每场战斗的战况，也可以通过#查看战报#来了解，请您过目。'
languagePack['dialog_cfg_info_9'] = '敌方大营兵力为0即可取胜！'
languagePack['dialog_cfg_info_10'] = '武将具有#【攻击距离】#，其普通攻击只能对距离内的敌方武将有效。'
languagePack['dialog_cfg_info_11'] = '当前敌方中军离我方的#距离为1#。'
languagePack['dialog_cfg_info_12'] = '当前敌方大营离我方的#距离为2#。'
languagePack['dialog_cfg_info_37'] = '贼军营地附近发现武将一名，已然带到。'
languagePack['dialog_cfg_info_13'] = '余使计掩隐入此，以图破贼，未料竟遇贤主，若不弃，愿效犬马之劳！'
languagePack['dialog_cfg_info_14'] = '我方又添一员良将，此乃吉兆，贼兵伏诛有望。'
languagePack['dialog_cfg_info_15'] = '部队配置的武将数越多，实力越强。'
languagePack['dialog_cfg_info_16'] = '如此，请将新将配置到部队#中军#位置。'
languagePack['dialog_cfg_info_17'] = '中军是部队的中坚力量，配合大营，可增强部队的实力。'
languagePack['dialog_cfg_info_18'] = '两将齐出，势必横扫流寇！'
languagePack['dialog_cfg_info_38'] = '余粮所剩无几，若无补给，形势不妙。'
languagePack['dialog_cfg_info_19'] = '所幸城外发现贼兵的辎重队，若能劫获此队，于我方大利！'
languagePack['dialog_cfg_info_20'] = '敌军兵力大于我军，此战不易！'
languagePack['dialog_cfg_info_21'] = '方才一战，胜之险甚，皆因我方兵力较少而致。'
languagePack['dialog_cfg_info_22'] = '如今辎重在手，劳烦您立即为我军#征兵#。'
languagePack['dialog_cfg_info_23'] = '#征兵需要时间#。征兵数越多，耗时越长。'
languagePack['dialog_cfg_info_24'] = '由于现在战况紧张，本次征兵可以立即完成。'
languagePack['dialog_cfg_info_39'] = '我军势小，多将方可统领多队，收复领地。'
languagePack['dialog_cfg_info_25'] = '闻得城外有在野良将出没，此际急需用人，理应尽快#招募#。'
languagePack['dialog_cfg_info_40'] = '新将加入，当整兵待战。'
languagePack['dialog_cfg_info_26'] = '下面请#升级校场#至Lv.2，即可配置两支部队。'
languagePack['dialog_cfg_info_27'] = '建造设施需要消耗一定时间，使用#玉符#能使建造中的设施#立即完成#。'
languagePack['dialog_cfg_info_28'] = '再获强队，当是如虎添翼！'
languagePack['dialog_cfg_info_29'] = '城外发现了武将经验书，可使武将快速提升等级。'
languagePack['dialog_cfg_info_30'] = '复地在即，贼军仅余两处，一鼓作气尽数攻占！'
languagePack['dialog_cfg_info_31'] = '贼兵已退，全城军民深感英雄高义，敬佩不已。'
languagePack['dialog_cfg_info_32'] = '如今乱世当道，豪强尽起，我等愿奉您为主，从此追随主公，四方征战，死而后已！'
languagePack['dialog_cfg_info_33'] = '您才智高绝，心怀民志，您的旗号必将辉耀天下！'
languagePack['dialog_cfg_info_34'] = '新势初起，万象待兴，您可经由#任务#，逐渐发展壮大。'
languagePack['dialog_cfg_info_35'] = '事有不明，可多阅读#任务简介#，步步为营、励精图治，定可成就大业。'
languagePack['dialog_cfg_info_41'] = '烦请您立即遣将成队，迎击贼军！'
languagePack['dialog_cfg_info_201'] = '当前拥有的#两个建造队列#，可使得#两个设施同时建造#。'
languagePack['dialog_cfg_info_202'] = '欢迎来到#“演武”#系统，这是一个与外界不相关、独立的战斗演练空间。'
languagePack['dialog_cfg_info_203'] = '您将可以任意使用属于自己的武将组成部队，来战胜敌方。'
languagePack['dialog_cfg_info_204'] = '在配置部队时，请留意其要求，同时每次战胜，您都将获得奖励。'
languagePack['dialog_cfg_info_205'] = '现在，请充分展现您的战斗才能，带领您的部队走向胜利！'
languagePack['dialog_cfg_info_206'] = '您可以了解到敌方部队的详情。#（可点击敌方武将卡牌查看详情）#'
languagePack['dialog_cfg_info_207'] = '下一步就是#配置武将#准备出战。'
languagePack['dialog_cfg_info_208'] = '恭喜您已击败一支敌军，请再接再厉，#继续选择目标部队#，战必克敌！'
languagePack['dialog_cfg_info_209'] = '教学演武第2关，请留意敌方全部以#“步兵”#出战。'
languagePack['dialog_cfg_info_210'] = '若我方以#“骑兵”#对阵，则胜之较易。'
languagePack['dialog_cfg_info_211'] = '教学演武第3关，敌方此次出战均为#“骑兵”#。'
languagePack['dialog_cfg_info_212'] = '骑兵速度快，每回合行动顺位靠前，然#“弓兵”#对之有优势。'
languagePack['dialog_cfg_info_213'] = '教学演武第4关，敌方此次出战均为#“弓兵”#。'
languagePack['dialog_cfg_info_214'] = '弓兵攻击距离较远，但对#“步兵”#造成的伤害有限。'
languagePack['dialog_cfg_info_215'] = '教学演武第5关，敌方武将因为#“攻击距离”#而调整了位置。'
languagePack['dialog_cfg_info_216'] = '武将的攻击距离内有敌方目标，才能发动普通攻击，相邻武将距离为1。'
languagePack['dialog_cfg_info_217'] = '教学演武第6关，敌方武将的#“攻击”#属性较高。'
languagePack['dialog_cfg_info_218'] = '攻击影响普通攻击和部分主动战法，您可留意战法的详细说明。'
languagePack['dialog_cfg_info_219'] = '教学演武第7关，敌方换用了#“谋略”#属性较高的武将。'
languagePack['dialog_cfg_info_220'] = '“受谋略影响”的战法的实际效果与谋略有关，谋略越高，效果越强。'
languagePack['dialog_cfg_info_221'] = '教学演武第8关，您将遇到敌方部队#“多兵种混合”#出战。'
languagePack['dialog_cfg_info_222'] = '根据敌方部队的具体配置，选择您的出战武将。'
languagePack['dialog_cfg_info_223'] = '教学演武第9关，敌方部队注重了#“防御”#属性的提升。'
languagePack['dialog_cfg_info_224'] = '针对#“攻击”#属性，防御可以下降受到攻击时的伤害。'
languagePack['dialog_cfg_info_225'] = '教学演武第10关，您需要通过#“攻城”#来占领目标城池。'
languagePack['dialog_cfg_info_226'] = '战胜守军即可发动攻城，对城池造成的伤害=#部队中武将的攻城属性之和#。'
languagePack['dialog_cfg_info_227'] = '请选择演武难度，这将影响敌方部队的实力和战利品的多少。'
languagePack['dialog_cfg_info_228'] = '恭喜您完成全部教学演武，进入其进阶模式--#“自由演武”#。'
languagePack['dialog_cfg_info_238'] = '您将面对各种敌方部队，请务必在出战前了解其阵容特点。'
languagePack['dialog_cfg_info_239'] = '每天您都有开启一轮新演武的机会，完成每轮演武可获得额外奖励。'
languagePack['dialog_cfg_info_240'] = '自由演武开始，祝您旗开得胜！'
languagePack['dialog_cfg_info_229'] = '使用#预备兵#进行征兵，#不需消耗时间#，但仍需消耗资源。'
languagePack['dialog_cfg_info_230'] = '请选择主城周围的一块城区进行扩建。'
languagePack['dialog_cfg_info_231'] = '请#拖动#武将卡到上方素材卡区域中。'
languagePack['dialog_cfg_info_232'] = '请从上方选择一个战法进行学习。'
languagePack['dialog_cfg_info_233'] = '请#拖动#武将卡到上方素材卡区域中。'
languagePack['dialog_cfg_info_234'] = '拆解战法需要#消耗#对应#武将卡#及一定#战法经验#。'
languagePack['dialog_cfg_info_235'] = '获得的新战法必须提升其#研究度到100%才能学习#。'
languagePack['dialog_cfg_info_236'] = '通过消耗#研究条件#中指定的武将卡可提升战法研究进度。'
languagePack['dialog_cfg_info_237'] = '属性点可任意分配到以上属性上。每#1属性点#可增加#对应属性1点#。'
languagePack['dialog_cfg_info_241'] = '提升部队#兵力#，是加强部队实力的#最有效途径#。\n武将#等级越高#，可携带#兵力越多#。'
languagePack['dialog_cfg_info_242'] = '请先提升部队总兵力到1500以上，再出征土地Lv.3.'
languagePack['dialog_cfg_info_243'] = '#普通攻击仅能攻击距离内的武将#。如敌我双方都有3名武将参战，我方前锋与敌方前锋距离为1；我方中军与敌方前锋距离为2，与敌方大营距离则为4。'
languagePack['dialog_cfg_info_244'] = '为确保武将能有效攻击，请检查部队中武将是否已合理配置。'
languagePack['guide_cfg_info_tips_content_1001'] = ''
languagePack['guide_cfg_info_tips_content_1002'] = ''
languagePack['guide_cfg_info_tips_content_1003'] = ''
languagePack['guide_cfg_info_tips_content_1004'] = ''
languagePack['guide_cfg_info_tips_content_1114'] = ''
languagePack['guide_cfg_info_tips_content_1120'] = ''
languagePack['guide_cfg_info_tips_content_1005'] = '点击主城'
languagePack['guide_cfg_info_tips_content_1122'] = '点击【城池】'
languagePack['guide_cfg_info_tips_content_1006'] = '点击【未配置】'
languagePack['guide_cfg_info_tips_content_1007'] = ''
languagePack['guide_cfg_info_tips_content_1008'] = '点击【武将配置】'
languagePack['guide_cfg_info_tips_content_1009'] = '拖动武将卡到大营'
languagePack['guide_cfg_info_tips_content_1010'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1011'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1012'] = ''
languagePack['guide_cfg_info_tips_content_1013'] = '点击【返回地图】'
languagePack['guide_cfg_info_tips_content_1014'] = '点击【土地】'
languagePack['guide_cfg_info_tips_content_1015'] = '点击【出征】'
languagePack['guide_cfg_info_tips_content_1016'] = '选择部队'
languagePack['guide_cfg_info_tips_content_1017'] = '点击【出征】'
languagePack['guide_cfg_info_tips_content_1023'] = ''
languagePack['guide_cfg_info_tips_content_1024'] = ''
languagePack['guide_cfg_info_tips_content_1025'] = ''
languagePack['guide_cfg_info_tips_content_1026'] = ''
languagePack['guide_cfg_info_tips_content_1027'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1115'] = ''
languagePack['guide_cfg_info_tips_content_1028'] = ''
languagePack['guide_cfg_info_tips_content_1029'] = ''
languagePack['guide_cfg_info_tips_content_1030'] = ''
languagePack['guide_cfg_info_tips_content_1031'] = ''
languagePack['guide_cfg_info_tips_content_1032'] = '点击主城'
languagePack['guide_cfg_info_tips_content_1123'] = '点击【城池】'
languagePack['guide_cfg_info_tips_content_1033'] = '点击【部队头像】'
languagePack['guide_cfg_info_tips_content_1034'] = ''
languagePack['guide_cfg_info_tips_content_1035'] = '点击【武将配置】'
languagePack['guide_cfg_info_tips_content_1036'] = '拖动武将卡到中军'
languagePack['guide_cfg_info_tips_content_1037'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1038'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1039'] = ''
languagePack['guide_cfg_info_tips_content_1040'] = '点击【返回地图】'
languagePack['guide_cfg_info_tips_content_1041'] = '点击【土地】'
languagePack['guide_cfg_info_tips_content_1042'] = '点击【出征】'
languagePack['guide_cfg_info_tips_content_1043'] = '选择部队'
languagePack['guide_cfg_info_tips_content_1044'] = '点击【出征】'
languagePack['guide_cfg_info_tips_content_1045'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1116'] = ''
languagePack['guide_cfg_info_tips_content_1046'] = ''
languagePack['guide_cfg_info_tips_content_1047'] = '点击【土地】'
languagePack['guide_cfg_info_tips_content_1048'] = '点击【扫荡】'
languagePack['guide_cfg_info_tips_content_1049'] = '选择部队'
languagePack['guide_cfg_info_tips_content_1050'] = '点击【扫荡】'
languagePack['guide_cfg_info_tips_content_1051'] = ''
languagePack['guide_cfg_info_tips_content_1052'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1053'] = ''
languagePack['guide_cfg_info_tips_content_1054'] = ''
languagePack['guide_cfg_info_tips_content_1055'] = '点击主城'
languagePack['guide_cfg_info_tips_content_1124'] = '点击【城池】'
languagePack['guide_cfg_info_tips_content_1056'] = '选择部队'
languagePack['guide_cfg_info_tips_content_1057'] = '点击【征兵】'
languagePack['guide_cfg_info_tips_content_1058'] = '拖动滑块到上限'
languagePack['guide_cfg_info_tips_content_1059'] = '拖动滑块到上限'
languagePack['guide_cfg_info_tips_content_1060'] = '点击【确定征兵】'
languagePack['guide_cfg_info_tips_content_1061'] = ''
languagePack['guide_cfg_info_tips_content_1062'] = ''
languagePack['guide_cfg_info_tips_content_1063'] = '点击【确定】'
languagePack['guide_cfg_info_tips_content_1064'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1065'] = '点击【返回地图】'
languagePack['guide_cfg_info_tips_content_1066'] = '点击【土地】'
languagePack['guide_cfg_info_tips_content_1067'] = '点击【出征】'
languagePack['guide_cfg_info_tips_content_1068'] = '选择部队'
languagePack['guide_cfg_info_tips_content_1069'] = '点击【出征】'
languagePack['guide_cfg_info_tips_content_1018'] = ''
languagePack['guide_cfg_info_tips_content_1019'] = ''
languagePack['guide_cfg_info_tips_content_1020'] = '点击【战报】'
languagePack['guide_cfg_info_tips_content_1021'] = '点击【战斗简报】查看战斗详情'
languagePack['guide_cfg_info_tips_content_1022'] = '点击【战况回放】'
languagePack['guide_cfg_info_tips_content_1070'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1117'] = ''
languagePack['guide_cfg_info_tips_content_1071'] = ''
languagePack['guide_cfg_info_tips_content_1072'] = '点击【土地】'
languagePack['guide_cfg_info_tips_content_1073'] = '点击【扫荡】'
languagePack['guide_cfg_info_tips_content_1074'] = '选择部队'
languagePack['guide_cfg_info_tips_content_1075'] = '点击【扫荡】'
languagePack['guide_cfg_info_tips_content_1076'] = '点击【招募】'
languagePack['guide_cfg_info_tips_content_1077'] = '选择【卡包】'
languagePack['guide_cfg_info_tips_content_1078'] = '点击【招募】'
languagePack['guide_cfg_info_tips_content_1079'] = '点击【关闭】'
languagePack['guide_cfg_info_tips_content_1080'] = '点击【关闭】'
languagePack['guide_cfg_info_tips_content_1118'] = ''
languagePack['guide_cfg_info_tips_content_1081'] = ''
languagePack['guide_cfg_info_tips_content_1082'] = '点击主城'
languagePack['guide_cfg_info_tips_content_1125'] = '点击【城池】'
languagePack['guide_cfg_info_tips_content_1083'] = '点击【设施】'
languagePack['guide_cfg_info_tips_content_1084'] = '点击【校场】'
languagePack['guide_cfg_info_tips_content_1085'] = '点击【升级】'
languagePack['guide_cfg_info_tips_content_1086'] = ''
languagePack['guide_cfg_info_tips_content_1087'] = '点击【立即完成】'
languagePack['guide_cfg_info_tips_content_1088'] = '点击【未配置】'
languagePack['guide_cfg_info_tips_content_1089'] = '点击【武将配置】'
languagePack['guide_cfg_info_tips_content_1090'] = '拖动武将卡到大营'
languagePack['guide_cfg_info_tips_content_1121'] = '拖动武将卡到中军'
languagePack['guide_cfg_info_tips_content_1092'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1093'] = '点击【返回】'
languagePack['guide_cfg_info_tips_content_1094'] = ''
languagePack['guide_cfg_info_tips_content_1095'] = '点击【返回地图】'
languagePack['guide_cfg_info_tips_content_1119'] = ''
languagePack['guide_cfg_info_tips_content_1096'] = '点击【土地】'
languagePack['guide_cfg_info_tips_content_1097'] = '点击【扫荡】'
languagePack['guide_cfg_info_tips_content_1098'] = '选择部队'
languagePack['guide_cfg_info_tips_content_1099'] = '点击【扫荡】'
languagePack['guide_cfg_info_tips_content_1100'] = ''
languagePack['guide_cfg_info_tips_content_1101'] = '点击【土地】'
languagePack['guide_cfg_info_tips_content_1102'] = '点击【出征】'
languagePack['guide_cfg_info_tips_content_1103'] = '选择部队'
languagePack['guide_cfg_info_tips_content_1104'] = '点击【出征】'
languagePack['guide_cfg_info_tips_content_1105'] = '点击【土地】'
languagePack['guide_cfg_info_tips_content_1106'] = '点击【出征】'
languagePack['guide_cfg_info_tips_content_1107'] = '选择部队'
languagePack['guide_cfg_info_tips_content_1108'] = '点击【出征】'
languagePack['guide_cfg_info_tips_content_1109'] = ''
languagePack['guide_cfg_info_tips_content_1110'] = ''
languagePack['guide_cfg_info_tips_content_1111'] = ''
languagePack['guide_cfg_info_tips_content_1112'] = ''
languagePack['guide_cfg_info_tips_content_1113'] = ''
languagePack['guide_cfg_info_tips_content_3001'] = ''
languagePack['guide_cfg_info_tips_content_3002'] = ''
languagePack['guide_cfg_info_tips_content_3003'] = ''
languagePack['guide_cfg_info_tips_content_3004'] = ''
languagePack['guide_cfg_info_tips_content_3005'] = ''
languagePack['guide_cfg_info_tips_content_3006'] = ''
languagePack['guide_cfg_info_tips_content_3007'] = ''
languagePack['guide_cfg_info_tips_content_3008'] = ''
languagePack['guide_cfg_info_tips_content_3009'] = ''
languagePack['guide_cfg_info_tips_content_3010'] = ''
languagePack['guide_cfg_info_tips_content_3011'] = ''
languagePack['guide_cfg_info_tips_content_3012'] = ''
languagePack['guide_cfg_info_tips_content_3013'] = ''
languagePack['guide_cfg_info_tips_content_3014'] = ''
languagePack['guide_cfg_info_tips_content_3015'] = ''
languagePack['guide_cfg_info_tips_content_3016'] = ''
languagePack['guide_cfg_info_tips_content_3017'] = ''
languagePack['guide_cfg_info_tips_content_3018'] = ''
languagePack['guide_cfg_info_tips_content_3019'] = ''
languagePack['guide_cfg_info_tips_content_3020'] = ''
languagePack['guide_cfg_info_tips_content_3021'] = ''
languagePack['guide_cfg_info_tips_content_3022'] = ''
languagePack['guide_cfg_info_tips_content_3023'] = ''
languagePack['guide_cfg_info_tips_content_3024'] = ''
languagePack['guide_cfg_info_tips_content_3025'] = ''
languagePack['guide_cfg_info_tips_content_3026'] = ''
languagePack['guide_cfg_info_tips_content_3027'] = ''
languagePack['guide_cfg_info_tips_content_3028'] = ''
languagePack['guide_cfg_info_tips_content_3029'] = ''
languagePack['guide_cfg_info_tips_content_3030'] = ''
languagePack['guide_cfg_info_tips_content_3031'] = ''
languagePack['guide_cfg_info_tips_content_3032'] = ''
languagePack['guide_cfg_info_tips_content_3033'] = ''
languagePack['guide_cfg_info_tips_content_3034'] = ''
languagePack['com_guide_cfg_info_tips_content_2001'] = '点击【前往】'
languagePack['com_guide_cfg_info_tips_content_2002'] = '点击【土地】'
languagePack['com_guide_cfg_info_tips_content_2003'] = '点击【出征】'
languagePack['com_guide_cfg_info_tips_content_2004'] = '点击【土地】'
languagePack['com_guide_cfg_info_tips_content_2005'] = '点击【出征】'
languagePack['com_guide_cfg_info_tips_content_2006'] = '点击【前往】'
languagePack['com_guide_cfg_info_tips_content_2007'] = '点击【内政】'
languagePack['com_guide_cfg_info_tips_content_2008'] = '点击【征收】'
languagePack['com_guide_cfg_info_tips_content_2009'] = ''
languagePack['com_guide_cfg_info_tips_content_2010'] = '点击【立即完成】'
languagePack['com_guide_cfg_info_tips_content_2011'] = '点击【立即完成】'
languagePack['com_guide_cfg_info_tips_content_2012'] = '返回主城'
languagePack['com_guide_cfg_info_tips_content_2013'] = '点击【主城】'
languagePack['com_guide_cfg_info_tips_content_2014'] = '选择目标部队'
languagePack['com_guide_cfg_info_tips_content_2015'] = '点击【下一步】'
languagePack['com_guide_cfg_info_tips_content_2016'] = '点击【征兵】'
languagePack['com_guide_cfg_info_tips_content_2017'] = ''
languagePack['com_guide_cfg_info_tips_content_2018'] = '点击【立即征兵】'
languagePack['com_guide_cfg_info_tips_content_2019'] = '拖动滑块'
languagePack['com_guide_cfg_info_tips_content_2020'] = '拖动滑块'
languagePack['com_guide_cfg_info_tips_content_2021'] = '点击【确定征兵】'
languagePack['com_guide_cfg_info_tips_content_2022'] = '进行扩建'
languagePack['com_guide_cfg_info_tips_content_2023'] = ''
languagePack['com_guide_cfg_info_tips_content_2024'] = '点击【战法】'
languagePack['com_guide_cfg_info_tips_content_2025'] = '点击【战法经验转化】'
languagePack['com_guide_cfg_info_tips_content_2026'] = ''
languagePack['com_guide_cfg_info_tips_content_2027'] = '选择转化方式'
languagePack['com_guide_cfg_info_tips_content_2028'] = '点击【战法图标】'
languagePack['com_guide_cfg_info_tips_content_2029'] = '点击【可学习图标】'
languagePack['com_guide_cfg_info_tips_content_2030'] = ''
languagePack['com_guide_cfg_info_tips_content_2031'] = '点击【拆解战法】'
languagePack['com_guide_cfg_info_tips_content_2032'] = ''
languagePack['com_guide_cfg_info_tips_content_2033'] = ''
languagePack['com_guide_cfg_info_tips_content_2034'] = ''
languagePack['com_guide_cfg_info_tips_content_2035'] = '提升战法研究度'
languagePack['com_guide_cfg_info_tips_content_2036'] = ''
languagePack['com_guide_cfg_info_tips_content_2037'] = ''




---------------------------------------------------------------
-------------------------- 前端本地推送 -----------------------
---------------------------------------------------------------
languagePack['alert_event'] = '斥候回报：城外有状况，请主公留意！'

---------------------------------------------------------------
------------------ errortips 配置 -----------------------------
---------------------------------------------------------------
---------------------
-------标题
---------------------

languagePack['errorTitle_3'] = '资源说明'

---------------------
-------正文
---------------------

languagePack['errorContent_215'] = '#要塞中部队位置已满，请撤退部队或升级堡垒#'
languagePack['errorContent_133'] = '#是否进行洗点以回收该武将全部已配点数？#'
languagePack['errorContent_146'] = '@【领地产量】@所有领地每小时的资源总产量\n'
languagePack['errorContent_147'] = '@【城市产量】@所有城市设施每小时的资源总产量\n'
languagePack['errorContent_148'] = '@【同盟加成】@同盟等级提升而获得的资源产量加成\n'
languagePack['errorContent_149'] = '@【维持消耗】@因武将卡所带兵力而引起的每小时产量消耗\n'
languagePack['errorContent_151'] = '@【城池加成】@同盟占领城池而获得的资源产量加成\n'
languagePack['errorContentTips_133'] = '倒计时结束后可进行免费洗点：'
languagePack['errorContentTips_134'] = '当前可进行免费洗点'


-----------------------------------------
--系统提示信息---------------------------
languagePack['game_log_1'] = '@H@队成功占领@N（A）@'
languagePack['game_log_13'] = '@H@队成功占领@N（A）@，R'
languagePack['game_log_14'] = '@H@队成功占领@N（A）@，税收提高@X@'
languagePack['game_log_2'] = '获得@N（A）@'
languagePack['game_log_3'] = '在@E@的攻击下，失去@N（A）@'
languagePack['game_log_4'] = '失去@N（A）@'
languagePack['game_log_5'] = '在@E@的攻击下，失去分城@N（A）@'
languagePack['game_log_6'] = '在@E@的攻击下，失去要塞@N（A）@'
languagePack['game_log_7'] = '在@E@的攻击下，主城被攻克，已沦陷'
languagePack['game_log_8'] = '敌方势力@E@来犯，目标@N（A）@'
languagePack['game_log_9'] = '与@E@于@N（A）@交战'
languagePack['game_log_10'] = '领地数过低，未失去领地'
languagePack['game_log_11'] = '由于沦陷，被@E@掠夺@R@'
languagePack['game_log_12'] = '从@E@掠夺@R@'
languagePack['game_log_21'] = '由于不能攻击，@H@队于@N（A）@未发生战斗'
languagePack['game_log_22'] = '由于关系变化，@H@队未能驻守于@N（A）@'
languagePack['game_log_23'] = '由于要塞不存在，@H@队未能调动于@A@'
languagePack['game_log_24'] = '由于目的地块处于保护期中，@H@队于@N（A）@未发生战斗'
languagePack['game_log_31'] = '@BLv.X@建造完成'
languagePack['game_log_32'] = '分城@N（A）@建造完成'
languagePack['game_log_33'] = '要塞@N（A）@建造完成'
languagePack['game_log_34'] = '@N（A）@放弃完成'
languagePack['game_log_41'] = '@H@征兵@X@人完成'
languagePack['game_log_51'] = '@H@的部队于@N（A）@屯田，获得@R@'
languagePack['game_log_52'] = '@H@的部队于@N（A）@屯田失败，未获得资源'
languagePack['game_log_101'] = '@H@的部队于@N（A）@练兵，获得@R@'
languagePack['game_log_102'] = '@H@的部队于@N（A）@练兵失败，未获得经验'
languagePack['game_log_61'] = '主城成功迁往@（A）@'
languagePack['game_log_62'] = '迁城被中断'
languagePack['game_log_71'] = '开始坚守'
languagePack['game_log_72'] = '坚守结束'
languagePack['game_log_73'] = '由于处于坚守中，@H@的部队从@N（A）@直接返回'
languagePack['game_log_81'] = '@H@的部队到达了@N（A）@，获得了新的卡包（@C@）'
languagePack['game_log_82'] = '@H@的部队到达了@N（A）@，获得了@R@'
languagePack['game_log_83'] = '@H@的部队战胜了@N（A）@处的贼兵，获得了@R@'
languagePack['game_log_84'] = '@H@的部队惜败于@N（A）@处的贼兵，未能获得战利品'
languagePack['game_log_91'] = '加入同盟@E@'
languagePack['game_log_92'] = '被移出同盟'
languagePack['game_log_121'] = '@H@的部队战胜了@N（A）@处的山寨守军，获得了@R@'
languagePack['game_log_122'] = '@H@的部队惜败于@N（A）@处的山寨守军，未能获得战利品'


---------------------
-------提示
---------------------
languagePack['building_expand_succeed_tips'] = '成功扩建'




languagePack['hero_float_att_tips_rarity'] = '@【稀有度】@稀有度越高，成长率越高。'
languagePack['hero_float_att_tips_lv'] = '@【等级】@等级越高属性越强，可携带兵力越多。'
languagePack['hero_float_att_tips_soldier'] = '@【兵力】@兵力越多，部队战斗时越强。\n@【征兵消耗】@@木材@ &  @铁矿@ &  @粮草@ &  每100兵消耗  &粮草/小时'
languagePack['hero_float_att_tips_energy'] = '@【体力】@每次部队行动队中武将需要消耗20体力。'
languagePack['hero_float_att_tips_cost'] = '@【Cost】@影响成长率和部队配置。'
languagePack['hero_float_att_tips_forces'] = '@【阵营】@武将所属阵营。'
languagePack['hero_float_att_tips_soldierType'] = '@【兵种】@骑克步，步克弓，弓克骑	'
languagePack['hero_float_att_tips_attackRange'] = '@【攻击距离】@普通攻击仅攻击距离内的武将。'
languagePack['hero_float_att_tips_attack'] = '@【攻击】@提高普通攻击的伤害和非谋略战法的效果。'
languagePack['hero_float_att_tips_defense'] = '@【防御】@降低受到普通攻击和非谋略战法攻击的伤害。'
languagePack['hero_float_att_tips_intel'] = '@【谋略】@提高谋略战法效果，降低受到谋略战法攻击的伤害'
languagePack['hero_float_att_tips_speed'] = '@【速度】@影响部队的移动速度和战斗中武将的出手顺序。	'
languagePack['hero_float_att_tips_attackCity'] = '@【攻城】@发动攻城时可降低目标的耐久度。'
languagePack['hero_float_att_tips_growRate'] = '@【成长率】@武将每次升级时提升的属性值。'


languagePack['first_person_name'] = '我'
languagePack['func_close_renwon_tips'] = '名望达到&开放'
languagePack['hero_can_teach_skill_tips'] = '3星及以上武将可以拆解战法'

languagePack['decree_not_enough_tips'] = '政令数不足'

languagePack['userOfficialTitle_tax'] = '今日税收'
languagePack['userOfficialTitle_trade'] = '交易'
languagePack['userOfficialTitle_strongHold'] = '坚守'
languagePack['userOfficialTitle_moveCity'] = '迁城'
languagePack['userOfficialTitle_ranger'] = '流浪'

languagePack['default_editor_tips'] = '请输入'


languagePack['MOVE_BTN_UNABLE_TYPE_GOLD_NOT_ENOUGH'] = ''
languagePack['MOVE_BTN_UNABLE_TYPE_NO_TARGET_CID'] = '请选择目标城市'
languagePack['MOVE_BTN_UNABLE_TYPE_CD'] = '冷却中'
languagePack['MOVE_BTN_UNABLE_TYPE_HAS_ARMY_OUTSIDE'] = '主城还有部队未返回'
languagePack['MOVE_BTN_UNABLE_TYPE_HAS_UNFINISHED_BUILDING'] = '主城还有建筑队列未完成'
languagePack['MOVE_BTN_UNABLE_TYPE_HAS_ARMY_RECRUIT'] = '主城还有征兵队列未完成'
languagePack['MOVE_BTN_UNABLE_TYPE_TARGET_CITY_IS_REMOVING'] = '目标分城正在放弃中'
languagePack['MOVE_BTN_UNABLE_TYPE_USERCITY_IS_OCCUPIED'] = '玩家已被附属'

languagePack['list_and_so_on'] = '等'
languagePack['mail_title_name_all_unionMember'] = '【全部同盟成员】'
languagePack['str_system'] = '事件'
languagePack['tax_source_type_npc_city'] = '守军城市'
languagePack['tax_source_type_building'] = '城内设施'

languagePack['army_cannot_move_tips_zhengbing'] = '武将征兵中'
languagePack['army_cannot_move_tips_no_engergy'] = '武将疲劳中'
languagePack['army_cannot_move_tips_hurt'] = '武将重伤中'
languagePack['army_cannot_move_tips_not_in_city'] = '部队不在本城'
