com_guide_id_list = {CONST_GUIDE_2001 = 2001, CONST_GUIDE_2002 = 2002, CONST_GUIDE_2003 = 2003, CONST_GUIDE_2004 = 2004, CONST_GUIDE_2005 = 2005, CONST_GUIDE_2006 = 2006, CONST_GUIDE_2007 = 2007, CONST_GUIDE_2008 = 2008, CONST_GUIDE_2009 = 2009, CONST_GUIDE_2010 = 2010, CONST_GUIDE_2011 = 2011, CONST_GUIDE_2012 = 2012, CONST_GUIDE_2013 = 2013, CONST_GUIDE_2014 = 2014, CONST_GUIDE_2015 = 2015, CONST_GUIDE_2016 = 2016, CONST_GUIDE_2017 = 2017, CONST_GUIDE_2018 = 2018, CONST_GUIDE_2019 = 2019, CONST_GUIDE_2020 = 2020, CONST_GUIDE_2021 = 2021, CONST_GUIDE_2022 = 2022, CONST_GUIDE_2023 = 2023, CONST_GUIDE_2024 = 2024, CONST_GUIDE_2025 = 2025, CONST_GUIDE_2026 = 2026, CONST_GUIDE_2027 = 2027, CONST_GUIDE_2028 = 2028, CONST_GUIDE_2029 = 2029, CONST_GUIDE_2030 = 2030, CONST_GUIDE_2031 = 2031, CONST_GUIDE_2032 = 2032, CONST_GUIDE_2033 = 2033, CONST_GUIDE_2034 = 2034, CONST_GUIDE_2035 = 2035, CONST_GUIDE_2036 = 2036, CONST_GUIDE_2037 = 2037, CONST_GUIDE_2038 = 2038, CONST_GUIDE_2039 = 2039}

com_guide_cfg_info = {}
com_guide_cfg_info[2001] = {bg_state = 0, dialog_id = 0, wait_ui_load = 1, ui_id_name = "TASK_UI", map_mask_area = 0, ui_finger_type = 2, ui_mask_reference = "Button_go", ui_mask_pos = "0,0,174,81,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2001"], tips_dir = 3, next_guide_id = 0}
com_guide_cfg_info[2003] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "MAP_MESSAGE_UI", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "panel_op/btn_3", ui_mask_pos = "0,0,198,78,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2003"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2005] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "MAP_MESSAGE_UI", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "panel_op/btn_3", ui_mask_pos = "0,0,198,78,0", hit_state = 0, tips_content = languagePack["com_guide_cfg_info_tips_content_2005"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2006] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "TASK_UI", map_mask_area = 0, ui_finger_type = 2, ui_mask_reference = "Button_go", ui_mask_pos = "0,0,174,81,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2006"], tips_dir = 3, next_guide_id = 0}
com_guide_cfg_info[2007] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "MAIN_INTERFACE_UI", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "tool_panel/btn_4", ui_mask_pos = "0,0,120,98,1", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2007"], tips_dir = 1, next_guide_id = 0}
com_guide_cfg_info[2008] = {bg_state = 0, dialog_id = 0, wait_ui_load = 1, ui_id_name = "UI_USER_OFFICIAL", map_mask_area = 0, ui_finger_type = 2, ui_mask_reference = "btn_ok_0", ui_mask_pos = "0,0,168,46,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2008"], tips_dir = 3, next_guide_id = 0}
com_guide_cfg_info[2009] = {bg_state = 0, dialog_id = 201, wait_ui_load = 0, ui_id_name = "BUILD_TREE_MANAGER", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "self;self", ui_mask_pos = "585,444,103,97,0;585,280,103,97,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2009"], tips_dir = 0, next_guide_id = 0}
com_guide_cfg_info[2010] = {bg_state = 0, dialog_id = 0, wait_ui_load = 1, ui_id_name = "BUILD_MSG_MANAGER", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "btn_quickComplete", ui_mask_pos = "0,0,168,46,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2010"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2011] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "BUILD_MSG_MANAGER", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "btn_quickComplete", ui_mask_pos = "0,0,168,46,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2011"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2012] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "MAIN_INTERFACE_UI", map_mask_area = 0, ui_finger_type = 2, ui_mask_reference = "btn_cityList_switch/img_tips", ui_mask_pos = "0,0,60,60,0", hit_state = 0, tips_content = languagePack["com_guide_cfg_info_tips_content_2012"], tips_dir = 3, next_guide_id = 0}
com_guide_cfg_info[2013] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "MAIN_INTERFACE_UI", map_mask_area = 0, ui_finger_type = 2, ui_mask_reference = "panel_list", ui_mask_pos = "120,20,241,50,0", hit_state = 0, tips_content = languagePack["com_guide_cfg_info_tips_content_2013"], tips_dir = 3, next_guide_id = 0}
com_guide_cfg_info[2014] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "EXERCISE_WHOLE_UI", map_mask_area = 1, ui_finger_type = 1, ui_mask_reference = "", ui_mask_pos = "", hit_state = 0, tips_content = languagePack["com_guide_cfg_info_tips_content_2014"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2015] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "EXERCISE_ENEMY_UI", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "next_btn", ui_mask_pos = "0,0,174,81,0", hit_state = 0, tips_content = languagePack["com_guide_cfg_info_tips_content_2015"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2016] = {bg_state = 0, dialog_id = 0, wait_ui_load = 1, ui_id_name = "ARMY_OVERVIEW_UI", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "op_img/zb_btn", ui_mask_pos = "0,1,140,135,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2016"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2017] = {bg_state = 0, dialog_id = 229, wait_ui_load = 1, ui_id_name = "CARD_ADD_SOLDIER", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "", ui_mask_pos = "", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2017"], tips_dir = 0, next_guide_id = 2018}
com_guide_cfg_info[2018] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "CARD_ADD_SOLDIER", map_mask_area = 0, ui_finger_type = 2, ui_mask_reference = "consume_panel/yb_img/yb_btn", ui_mask_pos = "0,0,174,81,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2018"], tips_dir = 0, next_guide_id = 0}
com_guide_cfg_info[2019] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "CARD_ADD_SOLDIER", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "pos_1/content_panel/slider_content", ui_mask_pos = "0,0,450,46,0", hit_state = 0, tips_content = languagePack["com_guide_cfg_info_tips_content_2019"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2020] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "CARD_ADD_SOLDIER", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "pos_2/content_panel/slider_content", ui_mask_pos = "0,0,450,46,0", hit_state = 0, tips_content = languagePack["com_guide_cfg_info_tips_content_2020"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2021] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "CARD_ADD_SOLDIER", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "btn_panel/confirm_btn", ui_mask_pos = "0,0,184,81,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2021"], tips_dir = 1, next_guide_id = 0}
com_guide_cfg_info[2022] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "MAIN_INTERFACE_UI", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "btn_op_3", ui_mask_pos = "0,0,87,87,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2022"], tips_dir = 2, next_guide_id = 0}
com_guide_cfg_info[2023] = {bg_state = 0, dialog_id = 230, wait_ui_load = 0, ui_id_name = "BUILD_EXPAND_TITLE", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "img_content", ui_mask_pos = "0,0,610,81,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2023"], tips_dir = 0, next_guide_id = 0}
com_guide_cfg_info[2024] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "MAIN_INTERFACE_UI", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "tool_panel/btn_3", ui_mask_pos = "0,0,120,98,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2024"], tips_dir = 1, next_guide_id = 2025}
com_guide_cfg_info[2025] = {bg_state = 0, dialog_id = 0, wait_ui_load = 1, ui_id_name = "UI_SKILL_OVERVIEW", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "scrollView/main_panel/item_transfer", ui_mask_pos = "85,100,193,85,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2025"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2026] = {bg_state = 0, dialog_id = 231, wait_ui_load = 0, ui_id_name = "UI_SKILL_OPERATE", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "panel_intro_2", ui_mask_pos = "263,-131,498,236,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2026"], tips_dir = 0, next_guide_id = 0}
com_guide_cfg_info[2027] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "UI_SKILL_OPERATE", map_mask_area = 0, ui_finger_type = 2, ui_mask_reference = "panel_op_1/btn_op_coin", ui_mask_pos = "0,0,174,81,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2027"], tips_dir = 3, next_guide_id = 0}
com_guide_cfg_info[2028] = {bg_state = 0, dialog_id = 0, wait_ui_load = 1, ui_id_name = "CARD_VIEWER_USER", map_mask_area = 0, ui_finger_type = 2, ui_mask_reference = "panel_skills/skill_item_1", ui_mask_pos = "48,35,100,100,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2028"], tips_dir = 3, next_guide_id = 0}
com_guide_cfg_info[2029] = {bg_state = 0, dialog_id = 0, wait_ui_load = 1, ui_id_name = "CARD_VIEWER_USER", map_mask_area = 0, ui_finger_type = 2, ui_mask_reference = "panel_skills/skill_item_2", ui_mask_pos = "48,35,100,100,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2029"], tips_dir = 3, next_guide_id = 0}
com_guide_cfg_info[2030] = {bg_state = 0, dialog_id = 232, wait_ui_load = 0, ui_id_name = "UI_SKILL_OVERVIEW", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "self", ui_mask_pos = "265,75,520,150,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2030"], tips_dir = 0, next_guide_id = 0}
com_guide_cfg_info[2031] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "UI_SKILL_OVERVIEW", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "scrollView/main_panel/item_study_new", ui_mask_pos = "75,75,150,150,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2031"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2032] = {bg_state = 0, dialog_id = 233, wait_ui_load = 0, ui_id_name = "UI_SKILL_OPERATE", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "panel_main_2/ImageView_742371", ui_mask_pos = "0,0,160,223,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2032"], tips_dir = 0, next_guide_id = 0}
com_guide_cfg_info[2033] = {bg_state = 0, dialog_id = 234, wait_ui_load = 0, ui_id_name = "UI_SKILL_OPERATE", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "panel_main_2/ImageView_742371;panel_op_2/btn_op_ji", ui_mask_pos = "0,0,160,223,0;0,0,151,61", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2033"], tips_dir = 0, next_guide_id = 0}
com_guide_cfg_info[2034] = {bg_state = 0, dialog_id = 235, wait_ui_load = 1, ui_id_name = "UI_SKILL_OVERVIEW", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "self", ui_mask_pos = "207,74,381,129,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2034"], tips_dir = 0, next_guide_id = 2035}
com_guide_cfg_info[2035] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "UI_SKILL_OVERVIEW", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "self", ui_mask_pos = "75,75,150,150,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2035"], tips_dir = 4, next_guide_id = 0}
com_guide_cfg_info[2036] = {bg_state = 0, dialog_id = 236, wait_ui_load = 0, ui_id_name = "UI_SKILL_DETAIL", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "main_bg/condition_study", ui_mask_pos = "401,38,794,70,0", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2036"], tips_dir = 0, next_guide_id = 0}
com_guide_cfg_info[2037] = {bg_state = 0, dialog_id = 237, wait_ui_load = 0, ui_id_name = "CARD_VIEWER_USER", map_mask_area = 0, ui_finger_type = 0, ui_mask_reference = "", ui_mask_pos = "", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2037"], tips_dir = 0, next_guide_id = 0}
com_guide_cfg_info[2038] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "MAIN_INTERFACE_UI", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "open_btn", ui_mask_pos = "0,0,54,54,1", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2038"], tips_dir = 1, next_guide_id = 0}
com_guide_cfg_info[2039] = {bg_state = 0, dialog_id = 0, wait_ui_load = 0, ui_id_name = "MAIN_INTERFACE_UI", map_mask_area = 0, ui_finger_type = 1, ui_mask_reference = "second_tool_panel/btn_11", ui_mask_pos = "0,0,120,98,1", hit_state = 1, tips_content = languagePack["com_guide_cfg_info_tips_content_2039"], tips_dir = 4, next_guide_id = 0}

