actionDefine = {
				initArmy = 14, --初始化
				passiveSkill = 21, --被动技能
				playSkillBefore = 22, --施放技能，攻前
				playSkillAfter = 23, --施放技能，攻后
				playAttack = 24, --攻击施放技能
				playPrepare = 25, --技能开始准备
				playPrepareing = 26, --技能准备中
				playInterrupt = 27, --技能被打断
				effectNow = 28, --对H施加了E的效果
				warInit = 205, --队伍初始化
				warBegin = 8,  --正式战斗开始
				win = 127, --胜利
				lose= 207, --失败
				draw = 206, --平局,还有战间休息
				drawNoRest = 233, --平局，没有战间休息
				allDead = 218,--同归于尽
				ignoreBegin = 215, --可忽略的开始
				ignoreEnd = 216,--可忽略的结束
				parallelBegin = 222, --技能一起执行的开始
				parallelEnd = 223, --技能一起执行的结束
				lackRange = 125, --攻击范围不足
				beatBackRangeLack = 221, --反击范围不足
				normalAttack = 219, --普通攻击,自定义
				lackNormalAttack=220, --普通攻击时范围不足，自定义的
				normalAttackFlag = 119, --普通攻击
				beatBack = 120, --反击
				heroEnd = 217, --武将动作结束
				loseArmy = 121, --攻前损失兵力
				loseArmyAfter = 122, --攻后损失兵力
				cannotFight = 123 , --无法再战
				normalParallelBegin = 213, --攻击一起执行开始
				normalParallelEnd = 214, --攻击一起执行结束
				skillRangeLack = 126, --技能有效范围内没有有效目标
				noHero = 130, --对方没有武将出战
				armyAfter = 224, --H战斗后兵力为D
				getResources = 142, --获得木材*200，粮食*100，钱*200，礼券1*22。","",""
				getExpCount = 136, --战后获得的经验
				levelUp = 225, --战后等级提升
				effectDisappear =102, --H的E消失了","",""
				effectExsit=29, -- {"H已存在E效果","8;H1",""}
				strongEffectExsit=210, -- {"H已存在更强E效果","8;H1",""}
				herolevel = 231, --武将等级提升后，换成这句话
				beforeWar = 4 ,--warRoundKeyword[4] = {"#战前回合开始#","",""}
				roundIndex = 9,--"#第#@D@#回合开始#","",""}
				defenceOfCity = 137, --对城防造成#@D@#点伤害,
				unionexp = 237, --同盟获得#@D@#经验
				wounded_soldier = 241, --伤兵数量
				animationBattle = 245, --数据统计
				}